### ISSUE TITLE
Definir paleta de cores do sistema

### ISSUE THREAD

**Issue by lilialnas** [ThierryMatheus/FiqueAlerta#17]
Definir paleta de cores do sistema

Sugestão:
1.  No máximo 3 cores 
2. Logotipo na paleta do cores
3.  Optar por estilo clean ( lembra do Google).

**Comment by Ingrid-st** [comment]
O que o Aplicativo visa?

-  Confiança - Azul
- Vigilância - Laranja
- Honestidade - Branco

Obs.: As cores ao lado direito fazem referência aos três adjetivos que a marca quer passar aos usuários do aplicativo.

**Comment by EsdrasPedro** [comment]
Paleta de Cores e tonalidades: 
Azul - #1919FF
Laranja - #FF8C00
Branco - #FFFFFF

**Comment by ranierivalenca** [comment]
- `#1919FF`
- `#FF8C00`
- `#FFFFFF`
