### ISSUE TITLE
Criação das rotas para cadastro do denunciante e empresa

### ISSUE THREAD

**Issue by gustavojms** [ThierryMatheus/FiqueAlerta#21]
Criação das rotas para o acesso correto das páginas de cadastro.

- [x] Criar rotas para o cadastro do usuário denunciante.
- [x] Criar rotas para o cadastro do usuário empresa.
- [x] Testar funcionalidade.

**Comment by huandersonlima** [comment]
Rota do cadastro do reclamante criada na issue #26

**Comment by gustavojms** [comment]
Rota do cadastro da empresa criada na issue #13
